version: 2

before:
  hooks:
    - go mod tidy

builds:
  -
    ldflags:
      - -s -w 
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ 'tar.gz' ]

snapshot:
  version_template: "{{ incpatch .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

